name: csv_fixer
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true